//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.08 at 11:55:13 AM CET 
//


package org.netbeans.gpx.model.factory;

import org.netbeans.gpx.model.entity.Bounds;
import org.netbeans.gpx.model.entity.Copyright;
import org.netbeans.gpx.model.entity.Email;
import org.netbeans.gpx.model.entity.Extensions;
import org.netbeans.gpx.model.entity.Gpx;
import org.netbeans.gpx.model.entity.GpxModel;
import org.netbeans.gpx.model.entity.Link;
import org.netbeans.gpx.model.entity.Metadata;
import org.netbeans.gpx.model.entity.Person;
import org.netbeans.gpx.model.entity.Point;
import org.netbeans.gpx.model.entity.PointSequence;
import org.netbeans.gpx.model.entity.Route;
import org.netbeans.gpx.model.entity.Track;
import org.netbeans.gpx.model.entity.TrackSegment;
import org.netbeans.gpx.model.entity.Waypoint;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.topografix package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Gpx_QNAME = new QName(GpxModel.Schema.NAME_SPACE.toString(), "gpx");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.topografix
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Gpx }
     * 
     */
    public Gpx createGpxType() {
        return new Gpx();
    }

    /**
     * Create an instance of {@link Waypoint }
     * 
     */
    public Waypoint createWptType() {
        return new Waypoint();
    }

    /**
     * Create an instance of {@link Bounds }
     * 
     */
    public Bounds createBoundsType() {
        return new Bounds();
    }

    /**
     * Create an instance of {@link Copyright }
     * 
     */
    public Copyright createCopyrightType() {
        return new Copyright();
    }

    /**
     * Create an instance of {@link Link }
     * 
     */
    public Link createLinkType() {
        return new Link();
    }

    /**
     * Create an instance of {@link Metadata }
     * 
     */
    public Metadata createMetadataType() {
        return new Metadata();
    }

    /**
     * Create an instance of {@link Extensions }
     * 
     */
    public Extensions createExtensionsType() {
        return new Extensions();
    }

    /**
     * Create an instance of {@link Route }
     * 
     */
    public Route createRteType() {
        return new Route();
    }

    /**
     * Create an instance of {@link Email }
     * 
     */
    public Email createEmailType() {
        return new Email();
    }

    /**
     * Create an instance of {@link PointSequence }
     * 
     */
    public PointSequence createPtsegType() {
        return new PointSequence();
    }

    /**
     * Create an instance of {@link Point }
     * 
     */
    public Point createPtType() {
        return new Point();
    }

    /**
     * Create an instance of {@link TrackSegment }
     * 
     */
    public TrackSegment createTrksegType() {
        return new TrackSegment();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPersonType() {
        return new Person();
    }

    /**
     * Create an instance of {@link Track }
     * 
     */
    public Track createTrkType() {
        return new Track();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Gpx }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.topografix.com/GPX/1/1", name = "gpx")
    public JAXBElement<Gpx> createGpx(Gpx value) {
        return new JAXBElement<Gpx>(_Gpx_QNAME, Gpx.class, null, value);
    }

}
