package org.netbeans.gpx.editor.panel;

import com.topografix.gpx.model.Link;

/**
 *
 * @author msc
 */
public class LinkDisplayPanel extends LinkPanel {

    public LinkDisplayPanel() {
        this(null);
    }

    /** Creates new form LinkDisplayPanel */
    public LinkDisplayPanel(Link link) {
        this.link = link;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        fillerLeft = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        lblLinkName = new javax.swing.JLabel();
        filler = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0));
        btnEditLink = new javax.swing.JButton();
        fillerRight = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        setOpaque(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));
        add(fillerLeft);

        lblLinkName.setMaximumSize(new java.awt.Dimension(150, 25));
        lblLinkName.setMinimumSize(new java.awt.Dimension(50, 25));
        lblLinkName.setPreferredSize(new java.awt.Dimension(150, 25));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${link.text}"), lblLinkName, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        add(lblLinkName);
        add(filler);

        btnEditLink.setText(org.openide.util.NbBundle.getMessage(LinkDisplayPanel.class, "LinkDisplayPanel.btnEditLink.text_1")); // NOI18N
        btnEditLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditLinkActionPerformed(evt);
            }
        });
        add(btnEditLink);
        add(fillerRight);

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditLinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditLinkActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditLink;
    private javax.swing.Box.Filler filler;
    private javax.swing.Box.Filler fillerLeft;
    private javax.swing.Box.Filler fillerRight;
    private javax.swing.JLabel lblLinkName;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
